language: php

php:
  - 5.5
  - 5.6

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls -v