language: php

php:
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install

script:
  - mkdir -p build/logs
  - phpunit -c app/phpunit.xml.dist

after_success:
  - bin/coveralls -v
