
services:

    ccmusic_search.api_client:
        class: %api_client_class%
        arguments: [ @logger ]

    ccmusic_search.service.jamendo_api_service:
        class: CCMusicSearchBundle\Service\JamendoApiService
        arguments: [ @ccmusic_search.api_client, %jamendo.base_uri%, %jamendo.api_key%, %jamendo.limit%, %cc_licenses% ]

    ccmusic_search.service.soundcloud_api_service:
        class: CCMusicSearchBundle\Service\SoundcloudApiService
        arguments: [ @ccmusic_search.api_client, %soundcloud.base_uri%, %soundcloud.api_key%, %soundcloud.limit%, %cc_licenses% ]

    ccmusic_search.service.ccmixter_api_service:
        class: CCMusicSearchBundle\Service\CCMixterApiService
        arguments: [ @ccmusic_search.api_client, %ccmixter.base_uri%, %ccmixter.api_key%, %ccmixter.limit%, %cc_licenses% ]

    ccmusic_search.twig.license_button_extension:
        class: CCMusicSearchBundle\Twig\LicenseButtonExtension
        arguments: [ %cc_license_url%, %cc_license_image%, %cc_licenses%, @logger ]
        tags:
            - { name: twig.extension }