parameters:

services:
    _defaults:
        public: true

    App\Service\JamendoApiService:
        class: App\Tests\Service\StubApiService
    App\Service\SoundcloudApiService:
        class: App\Tests\Service\StubApiService
    App\Service\CCMixterApiService:
        class: App\Tests\Service\StubApiService
    App\Service\Icons8ApiService:
        class: App\Tests\Service\StubApiService